//Testar as requisições - Schema Usuário
//Bye, Bye Postman :) (Mas claro, ainda dá para utilizá-lo se preferir)
//Instale a extensão REST Client no Visual Studio Code para conseguir utilizar este recurso


@baseUrl = http://localhost:4000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNWY2YzhjOWMxZmMyOGFiZDZlOTQxYjIyIn0sImlhdCI6MTYwMTA0ODgyNiwiZXhwIjoxNjAxMDUyNDI2fQ.uHvN0vHRLdaXl_GAop2CmU2ErJH_BhqqxDmzvJe2_Q4
###
// GET Obtendo os passeadores
GET {{baseUrl}}/passeador
Content-Type: application/json
x-access-token:  {{token}}


###
// POST Novo Passeador
POST {{baseUrl}}/passeador
Content-Type: application/json
x-access-token: {{token}}

{
    "nome": "Aparecida Ribeiro",
    "avatar": "https://source.unsplash.com/featured/?people,woman",
    "estrelas": 4.3,
    "favoritos": [
        {"usuarioId": "5f6c8c9c1fc28abd6e941b22"}
        ],
    "fotos": [
        {"url":"https://source.unsplash.com/featured/?dog"},
        {"url":"https://source.unsplash.com/featured/?puppy"}
        ],
    "testemunhos": [
        {"usuario":"Leana","estrelas":4,"texto":"Ótima profissional! A minha Mel é super bem cuidada por ela. Super recomendo!"},
        {"usuario":"Roberto","estrelas":5,"texto":"Simplesmente a melhor! Nunca me deixou na mão! Super indico se precisar viajar!"}
    ],
     "servicos": [
        {"nome":"Banho a domícilio","preco":40.00},
        {"nome":"Caminhadas diárias","preco":20.00}
    ]
}

###
// POST Novo Passeador
POST {{baseUrl}}/passeador
Content-Type: application/json
x-access-token: {{token}}

{
    "nome": "Renato Alves Penteado",
    "avatar": "https://source.unsplash.com/featured/?young,man",
    "estrelas": 2.5,
    "favoritos": [
        {"usuarioId": "5f6c8c9c1fc28abd6e941b22"}
        ],
    "fotos": [
        {"url":"https://source.unsplash.com/featured/?dog"},
        {"url":"https://source.unsplash.com/featured/?puppy"}
        ],
    "testemunhos": [
        {"usuario":"Mariana","estrelas":2,"texto":"Pensa em alguém que pisa na bola.É o Renato "},
        {"usuario":"Oswaldo","estrelas":3,"texto":"Infelizmente não recomendo o trabalho dele. Muito rude com os doguinhos."}
    ],
    "servicos": [
        {"nome":"Banho a domícilio","preco":40.00},
        {"nome":"Caminhadas 3X semana","preco":40.00},
        {"nome":"Banho e Tosa","preco":70.00},
        {"nome":"Adestramento (1h)","preco":50.00}
    ]
}

